### ISSUE TITLE
Does not run model tests!

### ISSUE THREAD

**Issue by starrychloe** [grosser/autotest#38]
With `autotest`

    C:\ruby200\bin\ruby -I.;lib;test -rubygems -e "['test/unit', 'test/controllers/admin_controller_test.rb', 'test/controllers/votes_controller_test.rb', 'test/integration/integration_helper.rb', 'test/helpers/posts_helper_test.rb', 'test/integration/comment_integration_test.rb', 'test/controllers/index_controller_test.rb', 'test/controllers/users_controller_test.rb', 'test/controllers/bitcoin_gateway_test.rb', 'test/helpers/comments_helper_test.rb', 'test/helpers/admin_helper_test.rb', 'test/controllers/comments_controller_test.rb', 'test/helpers/votes_helper_test.rb', 'test/integration/user_flows_test.rb', 'test/controllers/tags_controller_test.rb', 'test/helpers/user_helper_test.rb', 'test/helpers/tags_helper_test.rb', 'test/helpers/index_helper_test.rb', 'test/integration/post_integration_test.rb', 'test/controllers/posts_controller_test.rb'].each { |f| require f }" | ruby C:/ruby200/lib/ruby/gems/2.0.0/gems/autotest-standalone-4.5.11/bin/unit_diff -u
    62 tests, 187 assertions, 0 failures, 0 errors, 0 skips
    ruby -v: ruby 2.0.0p247 (2013-06-27) [i386-mingw32]

With `rake test`

    Finished tests in 26.777545s, 2.6515 tests/s, 7.4689 assertions/s.
    71 tests, 200 assertions, 0 failures, 0 errors, 0 skips

All the tests under `test/models/` are missing!

    *** LOCAL GEMS ***
    autotest-rails-pure (4.1.2)
    autotest-standalone (4.5.11)

**Comment by marko-avlijas** [comment]
What are alternatives?

**Comment by grosser** [comment]
https://www.ruby-toolbox.com/categories/continuous_testing

**Comment by marko-avlijas** [comment]
Thank you. It seems only guard is still maintained? It looked too complex when I was going through rails tutorial. I hope it can work in hassle-free mode.
